public enum MenuChoice {
    List_Home_OWNERS,
    List_Home_PROPERTIES,
    List_REGISTERED_VEHICLES,
    List_PROPERTY_ASSESSMENTS,
    DETAILS_FOR_ID,
    UPDATE_RECORD,
    ADD_NEW_RECORD,
    DELETE_RECORD,
    RETURN_TO_MAIN_MENU,
    NONE;
}
