public enum MenuChoice {
    LIST_HOME_OWNERS,
    LIST_HOME_PROPERTIES,
    LIST_REGISTERED_VEHICLES,
    LIST_PROPERTY_ASSESSMENTS,
    LIST_OWNERS_BY_ASSESSMENT,
    UPDATE_RECORD,
    ADD_NEW_RECORD,
    DELETE_RECORD,
    RETURN_TO_MAIN_MENU,
    NONE;
}
